// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Andrew J. Moore
//
// SourceBundler for MooreLib.Logger.
// Generates the standalone single-file distribution from the canonical source project.
//
// Project:
// https://github.com/bobapplemac/MooreLib.Logger

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Text;
using System.Xml.Linq;

internal class SourceBundler
{
    static int Main(string[] args)
    {
        if (args.Length != 2)
        {
            Console.Error.WriteLine("Usage: SourceBundler <source-project> <output-file>");
            return 1;
        }

        var projectFile = Path.GetFullPath(args[0]);
        var outputFile = Path.GetFullPath(args[1]);

        if (!File.Exists(projectFile))
        {
            Console.Error.WriteLine($"Source project does not exist: {projectFile}");
            return 1;
        }

        var sourceDirectory = Path.GetDirectoryName(projectFile)!;
        var fileVersion = ReadFileVersion(projectFile);

        var sourceFiles = Directory
            .EnumerateFiles(sourceDirectory, "*.cs", SearchOption.TopDirectoryOnly)
            .OrderBy(Path.GetFileName, StringComparer.OrdinalIgnoreCase)
            .ToArray();

        if (sourceFiles.Length == 0)
        {
            Console.Error.WriteLine($"No C# source files found in: {sourceDirectory}");
            return 1;
        }

        var parseOptions = CSharpParseOptions.Default.WithLanguageVersion(LanguageVersion.Latest);
        var externs = new Dictionary<string, string>(StringComparer.Ordinal);
        var usings = new Dictionary<string, string>(StringComparer.Ordinal);
        var attributes = new Dictionary<string, string>(StringComparer.Ordinal);
        var sections = new List<(string FileName, string Source)>();

        foreach (var sourceFile in sourceFiles)
        {
            var source = StripLeadingLicenseHeader(File.ReadAllText(sourceFile)).Replace("\r\n", "\n");
            var tree = CSharpSyntaxTree.ParseText(source, parseOptions, sourceFile);
            var errors = tree.GetDiagnostics().Where(d => d.Severity == DiagnosticSeverity.Error).ToArray();

            if (errors.Length != 0)
            {
                foreach (var error in errors)
                    Console.Error.WriteLine(error);

                return 1;
            }

            var root = tree.GetCompilationUnitRoot();

            AddDistinct(externs, root.Externs);
            AddDistinct(usings, root.Usings);
            AddDistinct(attributes, root.AttributeLists);

            var members = root.Members
                .Select(member => GetMemberSource(source, member))
                .Where(text => text.Length != 0);

            sections.Add((Path.GetFileName(sourceFile), string.Join("\n\n", members)));
        }

        var sb = new StringBuilder();
        sb.AppendLine("// SPDX-License-Identifier: MIT");
        sb.AppendLine("// Copyright (c) 2026 Andrew J. Moore");
        sb.AppendLine("//");
        sb.AppendLine("// MooreLib.Logger");
        sb.AppendLine($"// Source version: {fileVersion}");
        sb.AppendLine("//");
        sb.AppendLine("// Project:");
        sb.AppendLine("// https://github.com/bobapplemac/MooreLib.Logger");
        sb.AppendLine("//");
        sb.AppendLine("// GENERATED FILE - DO NOT EDIT.");
        sb.AppendLine("// Generated by Portable/SourceBundler from the canonical MooreLib.Logger source files.");
        sb.AppendLine("//");
        sb.AppendLine("// This file is provided as a single-file distribution of MooreLib.Logger.");
        sb.AppendLine("// Add the NLog package dependency to your project before using it.");
        sb.AppendLine("//");
        sb.AppendLine("// Licensed under the MIT License.");
        sb.AppendLine("// See the project repository for the full license text.");
        sb.AppendLine();

        AppendDirectives(sb, externs.Values);
        AppendDirectives(sb, usings.Values);
        AppendDirectives(sb, attributes.Values);

        foreach (var (fileName, source) in sections)
        {
            if (source.Length == 0)
                continue;

            sb.AppendLine($"#region {fileName}");
            sb.AppendLine();
            sb.AppendLine(source);
            sb.AppendLine();
            sb.AppendLine("#endregion");
            sb.AppendLine();
        }

        Directory.CreateDirectory(Path.GetDirectoryName(outputFile)!);
        File.WriteAllText(outputFile, sb.ToString(), new UTF8Encoding(false));

        Console.WriteLine($"Bundled {sourceFiles.Length} source files from MooreLib.Logger {fileVersion}:");
        Console.WriteLine(outputFile);
        return 0;

        static string ReadFileVersion(string projectFile)
        {
            var document = XDocument.Load(projectFile);
            var fileVersion = document
                .Descendants("FileVersion")
                .Select(element => element.Value.Trim())
                .FirstOrDefault(value => value.Length != 0);

            return fileVersion
                ?? throw new InvalidOperationException($"No FileVersion was found in '{projectFile}'.");
        }

        static string GetMemberSource(string source, MemberDeclarationSyntax member)
        {
            if (member is not FileScopedNamespaceDeclarationSyntax fileScoped)
                return Slice(source, member.FullSpan).Trim('\n');

            var name = Slice(source, fileScoped.Name.Span);
            var bodyStart = fileScoped.SemicolonToken.Span.End;
            var body = source[bodyStart..fileScoped.FullSpan.End].Trim('\n');

            return body.Length == 0
                ? $"namespace {name}\n{{\n}}"
                : $"namespace {name}\n{{\n{body}\n}}";
        }

        static string Slice(string source, TextSpan span) => source.Substring(span.Start, span.Length);

        static string StripLeadingLicenseHeader(string source)
        {
            source = source.Replace("\r\n", "\n");
            var lines = source.Split('\n');

            if (lines.Length < 2 ||
                !lines[0].StartsWith("// SPDX-License-Identifier:", StringComparison.Ordinal) ||
                !lines[1].StartsWith("// Copyright", StringComparison.Ordinal))
            {
                return source;
            }

            var firstContentLine = 2;
            while (firstContentLine < lines.Length && string.IsNullOrWhiteSpace(lines[firstContentLine]))
                firstContentLine++;

            return string.Join("\n", lines[firstContentLine..]);
        }

        static void AddDistinct<T>(Dictionary<string, string> destination, SyntaxList<T> nodes)
            where T : SyntaxNode
        {
            foreach (var node in nodes)
            {
                var value = node.ToString();
                var key = node.WithoutTrivia().ToString();
                destination.TryAdd(key, value);
            }
        }

        static void AppendDirectives(StringBuilder output, IEnumerable<string> directives)
        {
            var any = false;

            foreach (var directive in directives)
            {
                output.AppendLine(directive);
                any = true;
            }

            if (any)
                output.AppendLine();
        }
    }
}