<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
	<GenerateDependencyFile>false</GenerateDependencyFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageProjectUrl>https://github.com/bobapplemac/MooreLib.Logger</PackageProjectUrl>
    <Description>Structured, context-aware .NET logging built on NLog, with logical entries, progressive inline output, nested formatting, and structured properties.</Description>
    <Copyright>Copyright 2026 Andrew J. Moore</Copyright>
    <RepositoryUrl>https://github.com/bobapplemac/MooreLib.Logger</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <FileVersion>1.20.0.0</FileVersion>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
    <Title>MooreLib.Logger</Title>
    <ProduceReferenceAssembly>False</ProduceReferenceAssembly>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NLog" Version="6.2.0" />
  </ItemGroup>

</Project>
